// Services, prices and case content for "Послуги та прайс".
// Media renders through <MediaPlaceholder> — real files/URLs land in public/media/.

import mediaManifest from "./media-manifest.json";

const existingMedia = new Set<string>(mediaManifest);

export type Ratio = "9 / 16" | "4 / 5" | "16 / 10" | "6 / 5" | "16 / 9";

export type MediaKind = "image" | "video";

export type PriceRow = {
  label: string;
  value: string;
};

export type MediaItem = {
  id: string;
  kind: MediaKind;
  ratio: Ratio;
  alt: string;
  src?: string;
  poster?: string;
};

export type ServiceItem = {
  key: string;
  title: string;
  includes: string[];
  prices: PriceRow[];
  packagesTitle?: string;
  packages?: PriceRow[];
  note?: string;
  /** Case media for this service, used unless `mediaByFormat` is set. */
  media: MediaItem[];
  /** Дизайн only: 9:16 and 4:5 case sets never mix, keyed by the active format. */
  mediaByFormat?: Partial<Record<Ratio, MediaItem[]>>;
};

export type ServiceTabId = "design" | "video";

export type ServiceTab = {
  id: ServiceTabId;
  label: string;
  services: ServiceItem[];
};

function buildCases(
  idPrefix: string,
  count: number,
  kind: MediaKind,
  ratio: Ratio,
  altPrefix: string
): MediaItem[] {
  return Array.from({ length: count }, (_, i) => {
    const id = `${idPrefix}-${i}`;
    // Convention: drop a file at public/media/<id>.webp (photo, or video poster
    // frame) and it's picked up automatically — no code change needed. Until
    // the file exists (per media-manifest.json, regenerated by
    // scripts/build-media-manifest.mjs), <MediaPlaceholder> falls back to the
    // placeholder UI instead of requesting a file that 404s.
    const posterFile = `${id}.webp`;
    const videoFile = `${id}.mp4`;
    return {
      id,
      kind,
      ratio,
      alt: `${altPrefix} ${i + 1}`,
      ...(kind === "video"
        ? {
            ...(existingMedia.has(posterFile)
              ? { poster: `/media/${posterFile}` }
              : {}),
            ...(existingMedia.has(videoFile)
              ? { src: `/media/${videoFile}` }
              : {}),
          }
        : existingMedia.has(posterFile)
          ? { src: `/media/${posterFile}` }
          : {}),
    };
  });
}

export const SERVICE_TABS: ServiceTab[] = [
  {
    id: "design",
    label: "Дизайн",
    services: [
      {
        key: "design",
        title: "Дизайн",
        includes: [
          "Аналіз ніші",
          "Розробка візуальної концепції",
          "Підбір / генерація зображень (за потреби)",
          "Для креативів один ресайз 4:5 або 1:1 на вибір (або інші)",
        ],
        prices: [
          { label: "1 креатив", value: "450 грн" },
          { label: "Пост", value: "400 грн" },
          { label: "Карусель", value: "200 грн / слайд" },
          { label: "Історія", value: "200 грн" },
          { label: "Highlights (обкладинка)", value: "100 грн" },
          { label: "Додатковий ресайз", value: "50 грн" },
        ],
        packagesTitle: "Пакети статичних креативів",
        packages: [
          { label: "5 шт", value: "2 000 грн" },
          { label: "10 шт", value: "3 900 грн" },
          { label: "20 шт", value: "7 600 грн" },
        ],
        note: "Термін виконання: 1–2 дні (залежить від обʼєму).",
        media: [],
        mediaByFormat: {
          "9 / 16": buildCases(
            "ex-design-916",
            10,
            "image",
            "9 / 16",
            "Приклад дизайн-кейсу, формат 9:16, №"
          ),
          "4 / 5": buildCases(
            "ex-design-45",
            12,
            "image",
            "4 / 5",
            "Приклад дизайн-кейсу, формат 4:5, №"
          ),
        },
      },
      {
        key: "insta",
        title: "Упаковка Instagram",
        includes: [
          "Аналіз конкурентів для створення унікального візуалу",
          "Підбір шрифтів та палітри кольорів",
          "Розробка єдиної візуальної концепції стрічки",
          "Обкладинки Highlights (до 5 шт)",
        ],
        prices: [
          { label: "6 постів", value: "2 900 грн" },
          { label: "9 постів", value: "4 100 грн" },
        ],
        note: "Примітка: у вартість не включено каруселі, тому після обкладинки, наступний слайд каруселі оплачується окремо — 200 грн / слайд.",
        media: buildCases(
          "ex-insta",
          4,
          "image",
          "6 / 5",
          "Приклад упаковки Instagram, №"
        ),
      },
      {
        key: "decks",
        title: "Презентації",
        includes: [
          "Аналіз ніші",
          "Розробка візуальної концепції",
          "Підбір / генерація зображень (за потреби)",
        ],
        prices: [
          { label: "1–19 сторінок", value: "250 грн / слайд" },
          { label: "20–40 сторінок", value: "200 грн / слайд" },
          { label: "41+ сторінок", value: "150 грн / слайд" },
        ],
        note: "Примітка: для великих інфопродуктів вартість обговорюється індивідуально.",
        media: buildCases(
          "ex-decks",
          10,
          "image",
          "16 / 9",
          "Приклад презентації, №"
        ),
      },
    ],
  },
  {
    id: "video",
    label: "Монтаж відео",
    services: [
      {
        key: "basic",
        title: "Базовий монтаж",
        includes: [
          "Нарізка, видалення пауз та зведення матеріалу",
          "Базова кольорокорекція",
          "Підбір фонової музики",
          "2 кола правок включено у вартість",
        ],
        prices: [{ label: "до 1 хв", value: "від 11$" }],
        media: buildCases(
          "ex-basic",
          2,
          "video",
          "9 / 16",
          "Відео-кейс базового монтажу, №"
        ),
      },
      {
        key: "dynamic",
        title: "Динамічний монтаж / Відеокреатив",
        includes: [
          "Динамічна нарізка, видалення пауз, кольорокорекція, переходи",
          "Увага до Hook-ефекту (зачеплення уваги в перші 3 секунди)",
          "Дизайнерські анімовані субтитри з ручною розстановкою акцентів",
          "Моушн-дизайн та акцентування: плашки, вставки, графіка, анімація офферів, цін і CTA",
          "Підбір та/або AI-генерація унікального контенту (за потреби)",
          "Повний саунд-дизайн (SFX): очищення звуку, озвучка та фонова музика",
          "2 кола правок включено у вартість",
        ],
        prices: [
          { label: "до 30 секунд", value: "25$" },
          { label: "до 1 хв", value: "35$" },
        ],
        media: buildCases(
          "ex-dynamic",
          4,
          "video",
          "9 / 16",
          "Відео-кейс динамічного монтажу, №"
        ),
      },
      {
        key: "motion",
        title: "Motion",
        includes: [
          "Складна моушн-анімація та елементи графіки в After Effects",
          "Анімовані графічні елементи та інтерфейси",
          "Підбір та/або AI-генерація унікального контенту (за потреби)",
          "Повний саунд-дизайн (SFX): очищення звуку, озвучка та фонова музика",
          "2 кола правок включено у вартість",
        ],
        prices: [
          { label: "до 30 секунд", value: "50$" },
          { label: "до 1 хв", value: "70$" },
        ],
        media: buildCases("ex-motion", 4, "video", "9 / 16", "Моушн-кейс, №"),
      },
    ],
  },
];

export const STATS: PriceRow[] = [
  { label: "готових проєктів", value: "2800+" },
  { label: "роки роботи на фрілансі та в агенції", value: "4+" },
  { label: "пройдених навчань (маркетинг, дизайн, монтаж)", value: "9+" },
  { label: "місяців наставництва та менторства", value: "9+" },
];

export function perPageFor(ratio: Ratio): number {
  if (ratio === "16 / 10" || ratio === "16 / 9" || ratio === "6 / 5") return 1;
  if (ratio === "4 / 5") return 4;
  return 2;
}

export function mediaForService(service: ServiceItem, format: Ratio): MediaItem[] {
  if (service.mediaByFormat) {
    return service.mediaByFormat[format] ?? [];
  }
  return service.media;
}
